# Project Overview

The U.S. Department of Education organizes the College Scoreboard tool that gives students information on U.S. colleges. On the backend, the Department of Ed reports information collected from the Integrated Postsecondary Education Data System (IPEDS), Department of Treasury, and Internal Revenue Service. [For public use]<https://data.ed.gov/dataset/college-scorecard-all-data-files-through-6-2020/resources>, the Department of Ed published the datasets to encourage innovative use by others.<br><br>

The notebook assess the correlation between values of interest. High correlations and their respective indicators are collected for further investigation.

In [ ]:
import requests
import pandas as pd

In [2]:
df = pd.read_csv('data/most-recent-cohorts-all-data-elements.csv',sep=',',low_memory=False)

## Highly Correlated Indicators
Code belows identifies highly correlated columns of interest

In [5]:
columns_of_interest=[
'OPEID', 'INSTNM', 'CITY', 'STABBR', 'INSTURL', 
'CCUGPROF', 'HIGHDEG', 'CONTROL', 'LOCALE', 'LATITUDE', 'LONGITUDE', 
'CCSIZSET', 'HBCU', 'PBI', 'ANNHI', 'TRIBAL', 'AANAPII', 'HSI', 'NANTI', 
'MENONLY', 'WOMENONLY', 'RELAFFIL', 'ADM_RATE', 'UGDS', 'UG', 'UGDS_WHITE','UGDS_BLACK', 
'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 
'UGDS_UNKN', 'UGDS_WHITENH', 'UGDS_BLACKNH', 'UGDS_API', 'UGDS_AIANOLD', 
'UGDS_HISPOLD', 'UG_NRA', 'UG_UNKN', 'CURROPER', 
'NPT4_PUB', 'NPT4_PRIV', 'NPT41_PUB','NPT42_PUB', 'NPT43_PUB','NPT44_PUB', 'NPT45_PUB', 
'NPT41_PRIV', 'NPT42_PRIV', 'NPT43_PRIV', 'NPT44_PRIV', 'NPT45_PRIV', 
'TUITIONFEE_IN', 'TUITIONFEE_OUT', 'TUITFTE', 'INEXPFTE', 'PCTPELL', 
'C150_4', 'C150_4_WHITE', 'C150_4_BLACK', 'C150_4_HISP','C150_4_ASIAN', 
'C150_4_AIAN','C150_4_NHPI', 'C150_4_2MOR', 'C150_4_NRA', 
'C150_4_UNKN', 'C150_4_WHITENH', 'C150_4_BLACKNH', 'C150_4_API', 
'C150_4_AIANOLD', 'C150_4_HISPOLD', 
'CDR2', 'CDR3', 'LO_INC_COMP_ORIG_YR4_RT', 'MD_INC_COMP_ORIG_YR4_RT', 
'HI_INC_COMP_ORIG_YR4_RT', 'FEMALE_COMP_ORIG_YR4_RT', 'MALE_COMP_ORIG_YR4_RT', 
'FIRSTGEN_COMP_ORIG_YR4_RT', 'NOT1STGEN_COMP_ORIG_YR4_RT', 'LO_INC_COMP_ORIG_YR6_RT',
'MD_INC_COMP_ORIG_YR6_RT', 'HI_INC_COMP_ORIG_YR6_RT', 'PAR_ED_PCT_1STGEN', 
'DEP_INC_AVG', 'IND_INC_AVG', 'GRAD_DEBT_MDN', 'PELL_DEBT_MDN', 
'AGEGE24', 'FAMINC', 'MD_FAMINC', 'MEDIAN_HH_INC', 'COUNT_NWNE_P10', 
'COUNT_WNE_P10', 'MN_EARN_WNE_INC1_P10', 'MN_EARN_WNE_INC2_P10', 
'MN_EARN_WNE_INC3_P10', 'COUNT_NWNE_P6', 'COUNT_WNE_P6', 
'COUNT_NWNE_P7', 'COUNT_WNE_P7', 'COUNT_NWNE_P8', 'COUNT_WNE_P8', 
'COUNT_NWNE_P9', 'COUNT_WNE_P9', 'OPENADMP', 'D150_4_WHITE', 
'D150_4_BLACK', 'D150_4_HISP', 'D150_4_ASIAN', 'D150_4_AIAN', 
'D150_4_NHPI', 'D150_4_2MOR', 'D150_4_NRA', 'D150_4_UNKN', 
'RET_FT4_POOLED', 'RET_FT4_POOLED_SUPP', 'COUNT_NWNE_3YR', 'COUNT_WNE_3YR', 
]

In [6]:
#Creates new dataframe with columns of interest
project_data = df[columns_of_interest].copy().dropna(axis='columns',how='all')

project_data = project_data[project_data['CURROPER']==1]
project_data = project_data[project_data['CCUGPROF']>4]

corr = project_data.corr()
columns = corr.columns

In [7]:
#Creates a dataframe with correlation values that meets set threshold

#Sets correlation threshold
correlation_threshold = .6

high_corrs=pd.DataFrame()


for columns_x in columns:
    for columns_y in columns:
        value=corr.at[columns_x,columns_y]
        if (value > correlation_threshold or value < -correlation_threshold) and (columns_x!=columns_y):
            temp_df = pd.DataFrame([[columns_x,columns_y,value]],columns=['column 1','column 2','correlation'])
            high_corrs=pd.concat([high_corrs,temp_df])

            
high_corrs=high_corrs.reset_index().drop(columns='index')
high_corrs.sort_values(by='correlation')

           column 1        column 2  correlation
96   TUITIONFEE_OUT        NPT4_PUB     0.602387
20         NPT4_PUB  TUITIONFEE_OUT     0.602387
90    TUITIONFEE_IN       NPT42_PUB     0.603618
39        NPT42_PUB   TUITIONFEE_IN     0.603618
87       NPT45_PRIV          C150_4     0.604795
109          C150_4      NPT45_PRIV     0.604795
136     C150_4_UNKN    C150_4_WHITE     0.604957
123    C150_4_WHITE     C150_4_UNKN     0.604957
134     C150_4_2MOR    C150_4_BLACK     0.607068
128    C150_4_BLACK     C150_4_2MOR     0.607068
98   TUITIONFEE_OUT       NPT44_PUB     0.616734
52        NPT44_PUB  TUITIONFEE_OUT     0.616734
127    C150_4_BLACK     C150_4_HISP     0.620322
131     C150_4_HISP    C150_4_BLACK     0.620322
147  RET_FT4_POOLED    C150_4_WHITE     0.624743
124    C150_4_WHITE  RET_FT4_POOLED     0.624743
4          CCSIZSET    D150_4_WHITE     0.627321
139    D150_4_WHITE        CCSIZSET     0.627321
121    C150_4_WHITE     C150_4_HISP     0.628827
130     C150_4_HISP    C150_4_WHITE     0.628827
118    C150_4_WHITE  TUITIONFEE_OUT     0.631814
103  TUITIONFEE_OUT    C150_4_WHITE     0.631814
105         TUITFTE       NPT44_PUB     0.632779
53        NPT44_PUB         TUITFTE     0.632779
2          CCUGPROF       NPT45_PUB     0.635382
54        NPT45_PUB        CCUGPROF     0.635382
8              UGDS        CCSIZSET     0.637203
3          CCSIZSET            UGDS     0.637203
133     C150_4_2MOR    C150_4_WHITE     0.640046
122    C150_4_WHITE     C150_4_2MOR     0.640046
..              ...             ...          ...
101  TUITIONFEE_OUT   TUITIONFEE_IN     0.912288
95    TUITIONFEE_IN  TUITIONFEE_OUT     0.912288
80       NPT44_PRIV      NPT43_PRIV     0.913684
76       NPT43_PRIV      NPT44_PRIV     0.913684
74       NPT43_PRIV      NPT41_PRIV     0.914612
67       NPT41_PRIV      NPT43_PRIV     0.914612
111          C150_4    C150_4_WHITE     0.916724
119    C150_4_WHITE          C150_4     0.916724
25        NPT4_PRIV      NPT44_PRIV     0.921504
77       NPT44_PRIV       NPT4_PRIV     0.921504
50        NPT44_PUB       NPT45_PUB     0.932992
59        NPT45_PUB       NPT44_PUB     0.932992
43        NPT43_PUB       NPT44_PUB     0.936420
49        NPT44_PUB       NPT43_PUB     0.936420
70       NPT42_PRIV      NPT41_PRIV     0.936962
66       NPT41_PRIV      NPT42_PRIV     0.936962
75       NPT43_PRIV      NPT42_PRIV     0.937825
71       NPT42_PRIV      NPT43_PRIV     0.937825
40        NPT43_PUB        NPT4_PUB     0.944650
16         NPT4_PUB       NPT43_PUB     0.944650
149  COUNT_NWNE_3YR   COUNT_WNE_3YR     0.945853
151   COUNT_WNE_3YR  COUNT_NWNE_3YR     0.945853
46        NPT44_PUB        NPT4_PUB     0.946819
17         NPT4_PUB       NPT44_PUB     0.946819
42        NPT43_PUB       NPT42_PUB     0.955004
36        NPT42_PUB       NPT43_PUB     0.955004
35        NPT42_PUB       NPT41_PUB     0.959624
30        NPT41_PUB       NPT42_PUB     0.959624
13        UGDS_AIAN          TRIBAL     0.965931
6            TRIBAL       UGDS_AIAN     0.965931

[152 rows x 3 columns]

In [8]:
#Deletes duplicate rows with function

def create_key(row):
    if  row['column 1'] < row['column 2']:
        return row['column 1'] + row['column 2']
    else:
        return row['column 2'] + row['column 1'] 

high_corrs['Key'] = high_corrs.apply(create_key, axis=1)
high_corrs.drop_duplicates(subset ="Key", keep = 'first', inplace = True)
high_corrs = high_corrs.drop(columns='Key')
high_corrs

           column 1        column 2  correlation
0             OPEID  COUNT_NWNE_3YR     0.802546
1             OPEID   COUNT_WNE_3YR     0.707051
2          CCUGPROF       NPT45_PUB     0.635382
3          CCSIZSET            UGDS     0.637203
4          CCSIZSET    D150_4_WHITE     0.627321
5              HBCU      UGDS_BLACK     0.681345
6            TRIBAL       UGDS_AIAN     0.965931
7               HSI       UGDS_HISP     0.686479
9              UGDS    D150_4_WHITE     0.733126
10             UGDS     D150_4_2MOR     0.680133
14         NPT4_PUB       NPT41_PUB     0.886350
15         NPT4_PUB       NPT42_PUB     0.910481
16         NPT4_PUB       NPT43_PUB     0.944650
17         NPT4_PUB       NPT44_PUB     0.946819
18         NPT4_PUB       NPT45_PUB     0.885826
19         NPT4_PUB   TUITIONFEE_IN     0.769399
20         NPT4_PUB  TUITIONFEE_OUT     0.602387
21         NPT4_PUB         TUITFTE     0.642444
22        NPT4_PRIV      NPT41_PRIV     0.820628
23        NPT4_PRIV      NPT42_PRIV     0.813985
24        NPT4_PRIV      NPT43_PRIV     0.870404
25        NPT4_PRIV      NPT44_PRIV     0.921504
26        NPT4_PRIV      NPT45_PRIV     0.875257
27        NPT4_PRIV   TUITIONFEE_IN     0.651779
28        NPT4_PRIV  TUITIONFEE_OUT     0.651242
30        NPT41_PUB       NPT42_PUB     0.959624
31        NPT41_PUB       NPT43_PUB     0.909895
32        NPT41_PUB       NPT44_PUB     0.817816
33        NPT41_PUB       NPT45_PUB     0.682657
36        NPT42_PUB       NPT43_PUB     0.955004
..              ...             ...          ...
67       NPT41_PRIV      NPT43_PRIV     0.914612
68       NPT41_PRIV      NPT44_PRIV     0.832079
71       NPT42_PRIV      NPT43_PRIV     0.937825
72       NPT42_PRIV      NPT44_PRIV     0.853606
76       NPT43_PRIV      NPT44_PRIV     0.913684
81       NPT44_PRIV      NPT45_PRIV     0.739264
84       NPT45_PRIV   TUITIONFEE_IN     0.760936
85       NPT45_PRIV  TUITIONFEE_OUT     0.761146
86       NPT45_PRIV         TUITFTE     0.752651
87       NPT45_PRIV          C150_4     0.604795
95    TUITIONFEE_IN  TUITIONFEE_OUT     0.912288
102  TUITIONFEE_OUT          C150_4     0.649473
103  TUITIONFEE_OUT    C150_4_WHITE     0.631814
111          C150_4    C150_4_WHITE     0.916724
112          C150_4    C150_4_BLACK     0.775266
113          C150_4     C150_4_HISP     0.742109
114          C150_4     C150_4_2MOR     0.694839
115          C150_4     C150_4_UNKN     0.688171
116          C150_4  RET_FT4_POOLED     0.675376
120    C150_4_WHITE    C150_4_BLACK     0.660369
121    C150_4_WHITE     C150_4_HISP     0.628827
122    C150_4_WHITE     C150_4_2MOR     0.640046
123    C150_4_WHITE     C150_4_UNKN     0.604957
124    C150_4_WHITE  RET_FT4_POOLED     0.624743
127    C150_4_BLACK     C150_4_HISP     0.620322
128    C150_4_BLACK     C150_4_2MOR     0.607068
137            CDR2            CDR3     0.688873
141    D150_4_WHITE     D150_4_2MOR     0.712027
142    D150_4_ASIAN      D150_4_NRA     0.652833
149  COUNT_NWNE_3YR   COUNT_WNE_3YR     0.945853

[76 rows x 3 columns]

In [9]:
#Use the data dictionary to add the variables name to the dataframe

data_dictionary = pd.read_excel('data/collegescorecarddatadictionary.xlsx',sheet_name='institution_data_dictionary')
data_dictionary=data_dictionary[['NAME OF DATA ELEMENT','VARIABLE NAME']]
data_dictionary.columns

high_corrs_with_name=pd.merge(left=high_corrs,right=data_dictionary,left_on='column 1',right_on='VARIABLE NAME',how='left').drop(columns='VARIABLE NAME')
high_corrs_with_name=pd.merge(left=high_corrs_with_name,right=data_dictionary,left_on='column 2',right_on='VARIABLE NAME',how='left').drop(columns='VARIABLE NAME')

high_corrs_with_name=high_corrs_with_name.sort_values(by='column 1')

high_corrs_with_name

,column 1,column 2,correlation,NAME OF DATA ELEMENT_x,NAME OF DATA ELEMENT_y
60,C150_4,C150_4_BLACK,0.775266,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
64,C150_4,RET_FT4_POOLED,0.675376,"Completion rate for first-time, full-time stud...","First-time, full-time student retention rate a..."
62,C150_4,C150_4_2MOR,0.694839,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
61,C150_4,C150_4_HISP,0.742109,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
63,C150_4,C150_4_UNKN,0.688171,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
59,C150_4,C150_4_WHITE,0.916724,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
70,C150_4_BLACK,C150_4_HISP,0.620322,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
71,C150_4_BLACK,C150_4_2MOR,0.607068,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
69,C150_4_WHITE,RET_FT4_POOLED,0.624743,"Completion rate for first-time, full-time stud...","First-time, full-time student retention rate a..."
68,C150_4_WHITE,C150_4_UNKN,0.604957,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
67,C150_4_WHITE,C150_4_2MOR,0.640046,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
66,C150_4_WHITE,C150_4_HISP,0.628827,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
65,C150_4_WHITE,C150_4_BLACK,0.660369,"Completion rate for first-time, full-time stud...","Completion rate for first-time, full-time stud..."
3,CCSIZSET,UGDS,0.637203,Carnegie Classification -- size and setting,Enrollment of undergraduate certificate/degree...
4,CCSIZSET,D150_4_WHITE,0.627321,Carnegie Classification -- size and setting,Adjusted cohort count for completion rate of W...
2,CCUGPROF,NPT45_PUB,0.635382,Carnegie Classification -- undergraduate profile,"Average net price for $110,000+ family income ..."
72,CDR2,CDR3,0.688873,Two-year cohort default rate,Three-year cohort default rate
75,COUNT_NWNE_3YR,COUNT_WNE_3YR,0.945853,Number of graduates not working and not enroll...,Number of graduates working and not enrolled 3...
74,D150_4_ASIAN,D150_4_NRA,0.652833,Adjusted cohort count for completion rate of A...,Adjusted cohort count for completion rate of N...
73,D150_4_WHITE,D150_4_2MOR,0.712027,Adjusted cohort count for completion rate of W...,Adjusted cohort count for completion rate of s...
5,HBCU,UGDS_BLACK,0.681345,Flag for Historically Black College and Univer...,Total share of enrollment of undergraduate deg...
7,HSI,UGDS_HISP,0.686479,Flag for Hispanic-serving institution,Total share of enrollment of undergraduate deg...
47,NPT41_PRIV,NPT44_PRIV,0.832079,"Average net price for $0-$30,000 family income...","Average net price for $75,001-$110,000 family ..."
45,NPT41_PRIV,NPT42_PRIV,0.936962,"Average net price for $0-$30,000 family income...","Average net price for $30,001-$48,000 family i..."
46,NPT41_PRIV,NPT43_PRIV,0.914612,"Average net price for $0-$30,000 family income...","Average net price for $48,001-$75,000 family i..."
25,NPT41_PUB,NPT42_PUB,0.959624,"Average net price for $0-$30,000 family income...","Average net price for $30,001-$48,000 family i..."
26,NPT41_PUB,NPT43_PUB,0.909895,"Average net price for $0-$30,000 family income...","Average net price for $48,001-$75,000 family i..."
27,NPT41_PUB,NPT44_PUB,0.817816,"Average net price for $0-$30,000 family income...","Average net price for $75,001-$110,000 family ..."
28,NPT41_PUB,NPT45_PUB,0.682657,"Average net price for $0-$30,000 family income...","Average net price for $110,000+ family income ..."
48,NPT42_PRIV,NPT43_PRIV,0.937825,"Average net price for $30,001-$48,000 family i...","Average net price for $48,001-$75,000 family i..."
...,...,...,...,...,...
53,NPT45_PRIV,TUITIONFEE_OUT,0.761146,"Average net price for $110,000+ family income ...",Out-of-state tuition and fees
52,NPT45_PRIV,TUITIONFEE_IN,0.760936,"Average net price for $110,000+ family income ...",In-state tuition and fees
40,NPT45_PUB,TUITIONFEE_IN,0.808362,"Average net price for $110,000+ family income ...",In-state tuition and fees
41,NPT45_PUB,TUITIONFEE_OUT,0.695151,"Average net price for $110,000+ family income ...",Out-of-state tuition and fees
44,NPT45_PUB,C150_4_WHITE,0.644214,"Average net price for $110,000+ family income ...","Completion rate for first-time, full-time stud..."
43,NPT45_PUB,C150_4,0.660590,"Average net price for $110,000+ family income ...","Completion rate for first-time, full-time stud..."
42,NPT45_PUB,TUITFTE,0.675115,"Average net price for $110,000+ family income ...",Net tuition revenue per full-time equivalent s...
22,NPT4_PRIV,NPT45_PRIV,0.875257,Average net price for Title IV institutions (p...,"Average net price for $110,000+ family income ..."
18,NPT4_PRIV,NPT41_PRIV,0.820628,Average net price for Title IV institutions (p...,"Average net price for $0-$30,000 family income..."
19,NPT4_PRIV,NPT42_PRIV,0.813985,Average net price for Title IV institutions (p...,"Average net price for $30,001-$48,000 family i..."
23,NPT4_PRIV,TUITIONFEE_IN,0.651779,Average net price for Title IV institutions (p...,In-state tuition and fees
20,NPT4_PRIV,NPT43_PRIV,0.870404,Average net price for Title IV institutions (p...,"Average net price for $48,001-$75,000 family i..."
24,NPT4_PRIV,TUITIONFEE_OUT,0.651242,Average net price for Title IV institutions (p...,Out-of-state tuition and fees
21,NPT4_PRIV,NPT44_PRIV,0.921504,Average net price for Title IV institutions (p...,"Average net price for $75,001-$110,000 family ..."
12,NPT4_PUB,NPT43_PUB,0.944650,Average net price for Title IV institutions (p...,"Average net price for $48,001-$75,000 family i..."
17,NPT4_PUB,TUITFTE,0.642444,Average net price for Title IV institutions (p...,Net tuition revenue per full-time equivalent s...
16,NPT4_PUB,TUITIONFEE_OUT,0.602387,Average net price for Title IV institutions (p...,Out-of-state tuition and fees
15,NPT4_PUB,TUITIONFEE_IN,0.769399,Average net price for Title IV institutions (p...,In-state tuition and fees
14,NPT4_PUB,NPT45_PUB,0.885826,Average net price for Title IV institutions (p...,"Average net price for $110,000+ family income ..."
13,NPT4_PUB,NPT44_PUB,0.946819,Average net price for Title IV institutions (p...,"Average net price for $75,001-$110,000 family ..."
10,NPT4_PUB,NPT41_PUB,0.886350,Average net price for Title IV institutions (p...,"Average net price for $0-$30,000 family income..."
11,NPT4_PUB,NPT42_PUB,0.910481,Average net price for Title IV institutions (p...,"Average net price for $30,001-$48,000 family i..."
1,OPEID,COUNT_WNE_3YR,0.707051,8-digit OPE ID for institution,Number of graduates working and not enrolled 3...
0,OPEID,COUNT_NWNE_3YR,0.802546,8-digit OPE ID for institution,Number of graduates not working and not enroll...
6,TRIBAL,UGDS_AIAN,0.965931,Flag for tribal college and university,Total share of enrollment of undergraduate deg...
56,TUITIONFEE_IN,TUITIONFEE_OUT,0.912288,In-state tuition and fees,Out-of-state tuition and fees
57,TUITIONFEE_OUT,C150_4,0.649473,Out-of-state tuition and fees,"Completion rate for first-time, full-time stud..."
58,TUITIONFEE_OUT,C150_4_WHITE,0.631814,Out-of-state tuition and fees,"Completion rate for first-time, full-time stud..."
9,UGDS,D150_4_2MOR,0.680133,Enrollment of undergraduate certificate/degree...,Adjusted cohort count for completion rate of s...
8,UGDS,D150_4_WHITE,0.733126,Enrollment of undergraduate certificate/degree...,Adjusted cohort count for completion rate of W...

In [10]:
#This section is completely commented out to avoid creating excel export.

# Create a Pandas Excel writer using XlsxWriter as the engine.
#writer = pd.ExcelWriter('export.xlsx', engine='xlsxwriter')

# Position the dataframes in the worksheet.
#high_corrs_with_name.to_excel(writer, sheet_name='Sheet1')  # Default position, cell A1.

# Close the Pandas Excel writer and output the Excel file.
#writer.save()